---
# Sets up Home Assistant.
#
# Basically, everything that doesn't have to be in the
# main configuration.yaml.
#
homeassistant:
  # Name of the location where Home Assistant is running
  name: "PiVal Homeassistant"
  # Location required to calculate the time the sun rises and sets
  latitude: 49.0453086809979
  longitude: 2.013213663100481
  # 'metric' for Metric, 'imperial' for Imperial
  unit_system: Metric
  # Pick yours from here: https://en.wikipedia.org/wiki/List_of_tz_database_time_zones
  time_zone: "Europe/Paris"
  customize: !include_dir_merge_named ../customizations/entities
