---
alias: 'Switch Vals office light'
mode: queued
description: >-
  Controls the bathroom hue ceiling light with the sonoff mini switch
trigger:
  - platform: state
    entity_id: sensor.val_s_office_button
action:
  - service: light.toggle
    entity_id: light.val_s_office_light