language: python

python: "3.7"

before_install:
- mv travis_secrets.yaml secrets.yaml
- touch fullchain.pem
- touch privkey.pem
- sudo apt-get install -y libudev-dev

install:
- pip3 install homeassistant

script:
- hass -c . --script check_config
