language: python

python: "3.7"

before_install:
- mv travis_secrets.yaml secrets.yaml
- sudo mkdir -p /ssl/ && sudo touch /ssl/fullchain.pem
- sudo mkdir -p /ssl/ && sudo touch /ssl/privkey.pem
- sudo apt-get install -y libudev-dev

install:
- pip3 install homeassistant

script:
- hass -c . --script check_config
