---
alias: "Switch entry light"
mode: queued
description: Switch entry light
trigger:
  platform: state
  entity_id: sensor.control_home_switch
  to: "1_click"
action:
  - service: light.toggle
    entity_id: light.entry_light
