---
alias: "Turn lights on when tv on when sun is down"
mode: queued
description: >-
  Controls the living room light play when tv is on and when the sun is below horizon
trigger:
  - platform: state
    entity_id: sun.sun
    from: "above_horizon"
    to: "below_horizon"
condition:
  condition: state
  entity_id: sensor.tv_stand_on
  state: "True"
action:
  - service: scene.turn_on
    entity_id: scene.film_time
