---
alias: 'Switch bathroom ceiling off'
mode: queued
trigger:
  platform: state
  entity_id: switch.sonoff_mini_bathroom
  to: 'off'
action:
  - service: light.turn_off
    entity_id: light.hue_adore_spot_1
  - service: light.turn_off
    entity_id: light.hue_adore_spot_2
  - service: light.turn_off
    entity_id: light.hue_ambiance_wall_1