---
alias: "Notify laundry end"
mode: parallel
trigger:
  platform: state
  entity_id: sensor.machine_a_laver_le_linge_state
  to: "False"
  for:
    minutes: 20
action:
  - service: notify.mobile_app_mi_a3
    data:
      message: Valentin la machine a laver le linge est terminee
      title: Lave linge terminee
  - service: notify.mobile_app_priscillias_iphone
    data:
      message: Priscillia la machine a laver le linge est terminee
      title: Lave linge terminee
  - service: light.turn_on
    entity_id: light.yeelight_stripe_buandrie
