---
alias: 'Switch hallway ceiling off'
mode: queued
trigger:
  - platform: state
    entity_id:
      - switch.sonoff_mini_hallway
      - switch.hallway_switch_basic_relay
condition:
  - condition: state
    entity_id: 'light.hallway_lights'
    state: 'on'
action:
  - service: light.turn_off
    entity_id: light.hallway_lights