---
alias: "kitchen_light_switch_toggle"
mode: queued
trigger:
  - platform: state
    entity_id:
      - binary_sensor.kitchen_switch_basic_button
action:
  - service: light.toggle
    data: {}
    target:
      entity_id: light.kitchen_lights
