esphome:
  name: living-room-temp-humidity
  platform: ESP8266
  board: esp01_1m

wifi:
  ssid: "Freebox-PiVal"
  password: "A2295PiValNet0"

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "living-room-temp-humidity"
    password: "CMvPpUSO0yVm"

captive_portal:

# Enable logging
logger:

# Enable Home Assistant API
api:
  password: "Jslmdm0&"

ota:
  password: "Jslmdm0&"
  
sensor:
  - platform: dht
    pin: D2
    temperature:
      name: "Kitchen Temperature"
    humidity:
      name: "Kitchen Humidity"
    update_interval: 60s
