esphome:
  name: pilas-temp-humidity
  platform: ESP8266
  board: esp01_1m

wifi:
  ssid: "Freebox-PiVal"
  password: "A2295PiValNet0"

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "pilas-room-temp-humidity"
    password: "CMvPpUSO0yVm"

captive_portal:

# Enable logging
logger:

# Enable Home Assistant API
api:
  password: "Jslmdm0&"

ota:
  password: "Jslmdm0&"
  
sensor:
  - platform: dht
    pin: GPIO0
    model: DHT11
    temperature:
      name: "Pilas Room Temperature"
    humidity:
      name: "Pilas Room Humidity"
    update_interval: 60s
  - platform: wifi_signal
    name: "Pilas Room WiFi Signal Strength"
    update_interval: 60s
