---
esphome:
  name: temperature-humidity-bathroom
  platform: ESP8266
  board: esp8285
  
wifi:
  ssid: "Freebox-PiVal"
  password: "A2295PiValNet0"

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "Temperature-Humidity-Bathroom"
    password: "RLI2iw9hZSQx"

captive_portal:

# Enable logging
logger:

# Enable Home Assistant API
api:
  password: "Jslmdm0&"

ota:
  password: "Jslmdm0&"
     
sensor:
  - platform: wifi_signal
    name: "WiFi Signal Strength Bathroom"
    update_interval: 60s


status_led:
  pin:
    number: GPIO13
    inverted: yes